### ISSUE TITLE
LDraw viewer · Implementation

### ISSUE THREAD

**Issue by benedettoandrea** [GitHubDragonFly/GitHubDragonFly.github.io#1]
Hello! I just stumbled across this project of yours while researching on LDraw files, as I'm looking for a way to implement the example code (https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_ldraw.html) and having it running successfully online or locally. 
The main objective for me, although, would be to make it able to load/parse the files dynamically, as I'd like to manipulate the contents of the dat/ldr/mpd files and update on the fly those changes to create visual effects and experiment with this format for other means outside of their original purposes.
Since you made your own custom version, would you mind explaining the process you've gone through to code it? Also, do you think it would be possible to implement that function based on what already exists? 
Thanks in advance! :-)

**Comment by GitHubDragonFly** [comment]
Hello @benedettoandrea and thank you for showing the interest in my project.

Just remember that my project is public so you can either clone it or download a zip file and use/modify whatever you want for your purposes.

I have used the same three.js example you mentioned to code this LDRAW viewer, just like I did with all other three.js examples relevant to my other viewers. The process is somewhat simple, let user choose whether to load local or remote model files and then process those files for the displaying.

I am not sure whether you could create a functionality where you would manipulate the model files externally and then have the browser reflect those changes in the viewer on the fly and without reloading the whole model. Browsers are limited to what they can access locally so the user has to manually choose the files and load them - no browser should be able to fetch any subsequently modified version of the loaded file without the user intervention.

With the code as it is, you could keep the viewer open and manually reload the same local model as you make changes.

**Comment by GitHubDragonFly** [comment]
Also to mention that if you would ask the same question in the three.js forum ( https://discourse.threejs.org ) then somebody there might have a better idea of whether it is possible to implement this kind of functionality you have asked about.

**Comment by benedettoandrea** [comment]
Thank you for the detailed response, I really appreciate it. I will see what I'll be able to do :-)
